var deployed_contract = "0x554bfcc362f8feea2ba8fb7917e94ba0c15f8d37";

contracts = {};
ctrAddresses = {};
contracts["FitBlitz"] = {
	interface: [{"constant":false,"inputs":[{"name":"endTime","type":"uint256"}],"name":"EvaluateExercise","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_charity","type":"address"},{"name":"_startTime","type":"uint256"},{"name":"_targetDurationInMinutes","type":"uint256"}],"name":"BeginExercise","outputs":[],"payable":true,"type":"function"},{"inputs":[],"payable":false,"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"trainee","type":"address"},{"indexed":false,"name":"charity","type":"address"},{"indexed":false,"name":"donation","type":"uint256"},{"indexed":false,"name":"startTime","type":"uint256"},{"indexed":false,"name":"targetDurationInMinutes","type":"uint256"}],"name":"ExerciseBegun","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"trainee","type":"address"},{"indexed":false,"name":"charity","type":"address"},{"indexed":false,"name":"donation","type":"uint256"},{"indexed":false,"name":"targetDuration","type":"uint256"},{"indexed":false,"name":"measuredDuration","type":"uint256"}],"name":"ExerciseSuccessful","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"reason","type":"string"},{"indexed":false,"name":"trainee","type":"address"},{"indexed":false,"name":"charity","type":"address"},{"indexed":false,"name":"donation","type":"uint256"},{"indexed":false,"name":"targetDuration","type":"uint256"},{"indexed":false,"name":"measuredDuration","type":"uint256"}],"name":"ExerciseFailed","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"reason","type":"string"}],"name":"ErrorOcurred","type":"event"}],
	address: deployed_contract
};
contracts["FitBlitz"].contractClass = web3.eth.contract(contracts["FitBlitz"].interface);
contracts["FitBlitz"].contract = contracts["FitBlitz"].contractClass.at(contracts["FitBlitz"].address);
contracts["<FitBlitz - 0>"] = {
	interface: [{"constant":false,"inputs":[{"name":"endTime","type":"uint256"}],"name":"EvaluateExercise","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_charity","type":"address"},{"name":"_startTime","type":"uint256"},{"name":"_targetDurationInMinutes","type":"uint256"}],"name":"BeginExercise","outputs":[],"payable":true,"type":"function"},{"inputs":[],"payable":false,"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"trainee","type":"address"},{"indexed":false,"name":"charity","type":"address"},{"indexed":false,"name":"donation","type":"uint256"},{"indexed":false,"name":"startTime","type":"uint256"},{"indexed":false,"name":"targetDurationInMinutes","type":"uint256"}],"name":"ExerciseBegun","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"trainee","type":"address"},{"indexed":false,"name":"charity","type":"address"},{"indexed":false,"name":"donation","type":"uint256"},{"indexed":false,"name":"targetDuration","type":"uint256"},{"indexed":false,"name":"measuredDuration","type":"uint256"}],"name":"ExerciseSuccessful","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"reason","type":"string"},{"indexed":false,"name":"trainee","type":"address"},{"indexed":false,"name":"charity","type":"address"},{"indexed":false,"name":"donation","type":"uint256"},{"indexed":false,"name":"targetDuration","type":"uint256"},{"indexed":false,"name":"measuredDuration","type":"uint256"}],"name":"ExerciseFailed","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"reason","type":"string"}],"name":"ErrorOcurred","type":"event"}],
	address: deployed_contract
};
contracts["<FitBlitz - 0>"].contractClass = web3.eth.contract(contracts["<FitBlitz - 0>"].interface);
contracts["<FitBlitz - 0>"].contract = contracts["<FitBlitz - 0>"].contractClass.at(contracts["<FitBlitz - 0>"].address);
if (!ctrAddresses["FitBlitz"]){ ctrAddresses["FitBlitz"] = [] }ctrAddresses["FitBlitz"].push(deployed_contract)

